import Head from "next/head"
import Message from "../../components/message"

export default function Home() {
  return (
    <div>
       <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2 className="2-xl">See what everyone else if posting</h2>
        <Message />
        <Message />
      </div>
    </div>
    
  )
}